### ISSUE TITLE
Bug or not with local bus during creating a new user

### ISSUE THREAD

**Issue by grok-rs** [mprudnik/node-soa-template#10]
1. I configured a postgres db in compose file
2. Ran migrations
3. Tried to register a new user but received an error that you can see in the picture below

![image](https://user-images.githubusercontent.com/37833861/224047545-c24664ef-156a-46f6-ad6a-291a39ed1706.png)

**Comment by mprudnik** [comment]
Thank you for opening the issue!
Fixed in [c393c7139f3beef96def6bc7cb8faa605411fad3](https://github.com/mprudnik/node-soa-template/commit/c393c7139f3beef96def6bc7cb8faa605411fad3).
Please reopen this issue if it won't help.
