### ISSUE TITLE
Different serializers for passwords hex & base64

### ISSUE THREAD

**Issue by grok-rs** [mprudnik/node-soa-template#9]
https://github.com/mprudnik/node-soa-template/blob/main/src/lib/crypto.js

It throws an error with the wrong password,  it can't compare two different strings

**Comment by mprudnik** [comment]
Thank you for opening the issue!
Fixed in https://github.com/mprudnik/node-soa-template/commit/d2b601882c324dee4ed646f205f01795e1548df9.
Please reopen this issue if it won't help.
